import type { Metadata } from "next";
import React from "react";
import Nav_bar from "../components/Nav_Bar";
import MyQueryClientProvider from "../components/MyQueryClientProvider";
import '../global.css'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode
}

const RootLayout: React.FC<RootLayoutProps> = ({children})=> {

  return (
    <html lang="en">
      <body className="bg-[#242535]">
      <MyQueryClientProvider>
          <Nav_bar/>
          {children}
      </MyQueryClientProvider>

      </body>
    </html>
  );
}

export default RootLayout
